# fly.toml app configuration file generated for trivia-traitor-realtime-server on 2023-08-20T18:54:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trivia-traitor-realtime-server"
primary_region = "atl"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3002
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
